### ISSUE TITLE
Does Intesis have a local API

### ISSUE THREAD

**Issue by mhtrinh** [jnimmo/pyIntesisHome#46]
The library is working great ! Thank you for the  work ! 

I have a IS-RC3-RS485-WIFI-1-V2 module, aka Intesis AC Cloud Wifi. And was wonering if there is a local API to comunicate with the wifi module directly, without passing by the instesis server on internet ?

**Comment by lyricnz** [comment]
If this is possible, I would 100% prefer local!

**Comment by HeizOel** [comment]
there surely is one... im using it local since April i think it was the IntesisBox integration... but i had to search a bit to finally get it working. I even blocked the inteses internet connection in my router to prevent them from updating.

Edit: I think it was this integration https://github.com/jnimmo/hass-intesisbox it is using the WMP Protocol
